//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adglopez.Samples.ServiceBus.Auditing.Client.AuditProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Adglopez.Samples.ServiceBus.Auditing.Serv" +
        "ices")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessProcessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessProcess {
            get {
                return this.BusinessProcessField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessProcessField, value) != true)) {
                    this.BusinessProcessField = value;
                    this.RaisePropertyChanged("BusinessProcess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://adglopez.samples/servicebus/auditing", ConfigurationName="AuditProxy.IAuditService")]
    public interface IAuditService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="Audit")]
        void Audit(Adglopez.Samples.ServiceBus.Auditing.Client.AuditProxy.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="Audit")]
        System.Threading.Tasks.Task AuditAsync(Adglopez.Samples.ServiceBus.Auditing.Client.AuditProxy.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuditServiceChannel : Adglopez.Samples.ServiceBus.Auditing.Client.AuditProxy.IAuditService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuditServiceClient : System.ServiceModel.ClientBase<Adglopez.Samples.ServiceBus.Auditing.Client.AuditProxy.IAuditService>, Adglopez.Samples.ServiceBus.Auditing.Client.AuditProxy.IAuditService {
        
        public AuditServiceClient() {
        }
        
        public AuditServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuditServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuditServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuditServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Audit(Adglopez.Samples.ServiceBus.Auditing.Client.AuditProxy.CompositeType composite) {
            base.Channel.Audit(composite);
        }
        
        public System.Threading.Tasks.Task AuditAsync(Adglopez.Samples.ServiceBus.Auditing.Client.AuditProxy.CompositeType composite) {
            return base.Channel.AuditAsync(composite);
        }
    }
}
